# Generated by Django 4.1.4 on 2022-12-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_show_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
