# Generated by Django 4.1.4 on 2023-01-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_ticketlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlog',
            name='show',
        ),
        migrations.RemoveField(
            model_name='ticketlog',
            name='user',
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='Theater_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='hall_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='show_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='show_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='show_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
