# Generated by Django 4.1.4 on 2023-01-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_ticketlog_show_remove_ticketlog_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketlog',
            old_name='Theater_name',
            new_name='teater_name',
        ),
    ]
