# Generated by Django 4.1.4 on 2023-01-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_theater_name_ticketlog_teater_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlog',
            name='teater_name',
        ),
    ]
