# Generated by Django 4.1.4 on 2023-01-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_show_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='rate',
        ),
        migrations.AddField(
            model_name='show',
            name='alpha_range',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='rate1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='rate2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='rate3',
            field=models.IntegerField(null=True),
        ),
    ]
